config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#home"

  resources :vacations, except: [:show] do
    member do
      get 'print_voucher'
      get 'mark_paid'
    end
  end
  resources :misc_payments
  resources :bonuses
  resources :work_loans, only: [ :index, :new, :create, :destroy ]
  resources :departments
  resources :payslip_corrections
  resources :holidays, except: [:show, :new] do
    collection do
      post 'generate/:year', to: 'holidays#generate', as: :generate
    end
  end
  resources :standard_charge_notes, only: [:index, :create, :destroy]
  shallow do
    resources :employees do
      get 'search', on: :collection
      resources :children, except: [:show]
      resources :raises
      resources :loans, except: [:show] do
        resources :loan_payments, except: [:show, :index]
      end
      resources :bonuses, only: [ :index ] do
        collection do
          get 'list_possible', to: 'bonuses#index'
          patch 'unassign'
          patch 'assign'
        end
      end
      resources :work_loans, only: [ :index, :new, :create, :destroy ]
      resources :charges, except: [:edit, :update, :show]
      resources :misc_payments, except: [:edit, :update, :show]
      resources :vacations, except: :show do
        get 'days_summary', on: :collection
      end
      resources :payslips, only: [ :index, :show ]
    end
  end

  resources :supervisors, except: [:show]

  resources 'payslips', only: [ :index, :show ] do
    collection do
      post 'print_multi'
    end
  end

  # Reports index
  get 'reports', to: 'reports#index'
  get 'report_display', to: 'reports#show'
  get 'reports/*report', to: 'home#home' # eliminate gem routes
  get 'multi/reports/*report', to: 'home#home' # eliminate gem routes

  # Payslips
  post 'payslips/process', to: 'payslips#process_employee', as: :payslip_process_employee
  post 'payslips/process_complete', to: 'payslips#process_employee_complete', as: :payslip_process_employee_complete
  post 'payslips/process_all', to: 'payslips#process_all_employees', as: :payslip_process_all
  post 'payslips/process_all_nonrfis', to: 'payslips#process_nonrfis_employees', as: :payslip_process_nonrfis
  post 'payslips/process_all_rfis', to: 'payslips#process_rfis_employees', as: :payslip_process_rfis
  post 'payslips/process_all_bro', to: 'payslips#process_bro_employees', as: :payslip_process_bro
  post 'payslips/process_all_gnro', to: 'payslips#process_gnro_employees', as: :payslip_process_gnro
  post 'payslips/process_all_av', to: 'payslips#process_av_employees', as: :payslip_process_av
  post 'payslips/view_print_nonrfis', to: 'payslips#view_print_nonrfis', as: :view_print_nonrfis
  post 'payslips/view_print_rfis', to: 'payslips#view_print_rfis', as: :view_print_rfis
  post 'payslips/view_print_bro', to: 'payslips#view_print_bro', as: :view_print_bro
  post 'payslips/view_print_gnro', to: 'payslips#view_print_gnro', as: :view_print_gnro
  post 'payslips/view_print_av', to: 'payslips#view_print_av', as: :view_print_av
  post 'payslips/view_print_all', to: 'payslips#view_print_all', as: :view_print_all
  post 'payslips/post_period', to: 'payslips#post_period', as: :payslip_post_period
  post 'payslips/unpost_period', to: 'payslips#unpost_period', as: :payslip_unpost_period

  # Work Hours
  get 'workhours', to: 'work_hours#index', as: :work_hours
  get 'employees/:employee_id/work_hours',      to: 'work_hours#index', as: :employee_work_hours
  get 'employees/:employee_id/work_hours/edit', to: 'work_hours#edit',  as: :edit_employee_work_hours
  post 'employees/:employee_id/work_hours',    to: 'work_hours#update', as: :update_employee_work_hours
  post 'employees/work_hours_fill_all', to: 'work_hours#update_all', as: :fill_all_employees_work_hours

  # Administration
  get 'admin/index'
  get 'admin/manage_variables'
  get 'admin/manage_wages'
  get 'admin/manage_wage_show'
  get 'admin/journal_report'
  post 'admin/manage_wage_show', to: 'admin#manage_wage_update'
  get 'admin/timesheet', to: 'admin#timesheet', as: :generate_timesheets
  get 'admin/timesheets', to: 'admin#timesheets', as: :timesheet_pdf
  get 'admin/estimatepay', to: 'admin#estimate_pay', as: :estimate_pay
  post 'admin/estimate', to: 'admin#estimate_pay_process', as: :estimate_pay_post

  resources :users, except: [ 'show' ]

  # Session Controller
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Mock Controller
  get 'mock', to: "mock#home"
  get 'mock_employees', to: 'mock#employees'
  get 'mock_vacation', to: 'mock#vacation'
  get 'charges', to: 'mock#charges'
  get 'hours/edit', to: 'mock#hours_edit'
end

app/models/vacation.rb
include ApplicationHelper

class Vacation < ApplicationRecord

  MONTHLY = 12.0
  YEAR = 365

  attr :tax

  belongs_to :employee

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start
  validate :doesnt_overlap_existing
  validate :dont_violate_posted_period
  validate :cant_modify_if_already_paid

  default_scope { order(:start_date) }

  def save(*args)
    if super(*args)
      remove_overlapped_work_hours
      true
    else
      false
    end
  end

  def save!(*args)
    if super(*args)
      remove_overlapped_work_hours
      true
    else
      false
    end
  end

  def days
    number_of_days(start_date, end_date)
  end

  # NB. If two period have the same number of vacation
  # days, the earlier month will be returned.
  def apply_to_period
    start_period = Period.from_date(start_date)
    end_period = Period.from_date(end_date)

    if (start_period == end_period)
      return start_period
    end

    tmp_period = start_period
    period_with_most_days = tmp_period
    most_days = 0

    while (tmp_period <= end_period)
      tmp_period_days = days_in_period(tmp_period)

      if (tmp_period_days > most_days)
        most_days = tmp_period_days
        period_with_most_days = tmp_period
      end

      tmp_period = tmp_period.next
    end

    period_with_most_days
  end

  # NOTE: This only figures days used in period
  # for *this* vacation, not all vacations in
  # the period
  def days_in_period(period)
    return 0 if (end_date < period.start)
    return 0 if (start_date > period.finish)

    tmp_start_date = period.start
    tmp_end_date = period.finish

    # We overlap in some way, figure out which
    if (start_date > period.start)
      tmp_start_date = start_date
    end

    if (end_date < period.finish)
      tmp_end_date = end_date
    end

    number_of_days(tmp_start_date, tmp_end_date)
  end

  def overlaps_work_hours?
    not overlapped_work_hours(false).empty?
  end

  def overlapped_work_hours(include_zeros=true)
    return [] unless valid?
    where = 'date BETWEEN ? AND ?'
    where += ' AND hours > 0' unless include_zeros
    employee.work_hours.where(where, start_date, end_date)
  end

  def destroy
    if destroyable?
      super
    else
      false
    end
  end

  def destroyable?
    (not LastPostedPeriod.in_posted_period? start_date) && (not self[:paid])
  end

  def editable?
    (not LastPostedPeriod.in_posted_period? end_date) && (not self[:paid])
  end

  def self.for_period(period = Period.current)
    Vacation.where(overlap_clause(period.start, period.finish))
  end

  def self.starts_in(employee, period = Period.current)
    Vacation.where("employee_id = ?", employee&.id).
        where("start_date BETWEEN ? AND ?", period.start, period.finish)
  end

  def self.for_period_for_employee(employee, period = Period.current)
    Vacation.where(overlap_clause(period.start, period.finish)).where("employee_id = ?", employee.id)
  end

  def self.upcoming_vacations
    Vacation.all.where("start_date > ?", Period.current.finish)
  end

  # FIXME : Verify algorithm.
  def self.days_earned(employee, period)
    return 0 if period.finish < employee.first_day
    return 0 unless employee.accrues_vacation?
    earned = SystemVariable.value(:vacation_days).fdiv(MONTHLY)
    earned + period_supplemental_days(employee, period)
  end

  def self.period_supplemental_days(employee, period)
    return 0 unless employee.accrues_vacation?

    mom_days = mom_supplemental_days(employee)

    years_diff = (period.finish.year - Period.from_date(employee.contract_start).finish.year)
    years = (years_diff).div(SystemVariable.value(:supplemental_days_period))
    days = (years * SystemVariable.value(:supplemental_days).fdiv(MONTHLY.to_f) + mom_days)

    days = 0 if (days < 0)

    days
  end

  def self.first_supplemental_accrual_period(employee)
    # The period after the 4th anniversary
    anniv = (employee.contract_start.to_datetime >> (
        (SystemVariable.value(:supplemental_days_period) - 1) * MONTHLY
    )).next_month
    Period.new(anniv.year, anniv.month)
  end

  def self.mom_supplemental_days(employee)
    if employee.female?
      ( 2 * employee.children_under_6 ).fdiv(MONTHLY)
    else
      0
    end
  end

  def self.days_used(employee, period)
    days = RecursiveHashMerger.merge Vacation.days_hash(employee, period.start, period.finish),
                                     Holiday.days_hash(period.start, period.finish)
    used = 0
    days.each do |date, day|
      if day[:vacation] and not is_off_day?(date, day[:holiday])
        used += 1
      end
    end
    used
  end

  # FIXME: move?
  # If the period is posted, look in the payslip.
  # Otherwise, guess -- since things are going
  # change anyways.
  def self.balance(employee, period)
    if LastPostedPeriod.posted? period
      payslip = employee.payslip_for period
      return payslip.nil? ? 0 : payslip.vacation_balance
    else
      payslip = employee.payslip_for LastPostedPeriod.get
      start_period = payslip.nil? ? Period.from_date(employee.first_day).previous
                         : LastPostedPeriod.get
      balance = payslip.nil? ? 0 : payslip.vacation_balance
      (start_period.next .. period).each do |p|
        balance = balance + days_earned(employee, p) - days_used(employee, p)
      end
    end
    balance
  end

  def self.on_vacation_during(employee, start, finish)
    check_date = start
    while check_date <= finish
      vacation = employee.vacations.find_by("start_date <= :date AND end_date >= :date", date: check_date)
      return false unless vacation
      check_date = vacation.end_date + 1
    end
    return true
  end

  def self.days_hash(employee, start, finish)
    vacations = employee.vacations.where(overlap_clause(start, finish))
    vdays = {}
    (start .. finish).each do |date|
      vdays[date] = {vacation: true} if vacations.any?{ |vacay| (vacay.start_date .. vacay.end_date) === date }
    end
    vdays
  end

  # Only the payslip knows
  def self.vacation_daily_rate(employee)
    # Previous algorithm just used cnps wage as parameter
    # then figured out how much vacation pay is for that
    # (1/16th), per day.

    # This will look at the most recent payslip for this user.
    # and determine a few things from there.
    payslip = Payslip.most_recent(employee)
    payslip.vacation_daily_rate
  end

  def prep_print
    vacation_pay
  end

  def mark_paid
    prep_print
    self[:paid] = true
  end

  # Compute vacation pay for this vacation based on balances
  # in employee's payslip.
  def vacation_pay(payslip=nil)
    period = Period.from_date(start_date)

    applied_period = apply_to_period
    self[:period_month] = applied_period.month
    self[:period_year] = applied_period.year

    # if not passed in, attempt to find payslip
    if (payslip.nil?)
      payslip = Payslip.most_recent(employee)
    end

    return 0 if payslip.nil?
    return 0 if payslip.vacation_pay_balance.nil?
    return 0 if payslip.vacation_balance == 0

    # FIXME similar to payslip line 794
    self[:vacation_pay] = ( payslip.vacation_daily_rate * days ).round

    # This may need some cleanup
    tax = Tax.compute_taxes(employee, self[:vacation_pay], self[:vacation_pay])
    self[:ccf] = tax.ccf
    self[:crtv] = tax.crtv
    self[:proportional] = tax.proportional
    self[:cac] = tax.cac
    self[:cac2] = tax.cac2
    self[:communal] = tax.communal
    self[:cnps] = tax.cnps
    self[:total_tax] = tax.total_tax

    self[:vacation_pay]
  end

  def net_pay
    vacation_pay - (get_tax().total_tax())
  end

  def pay_per_period(period)
    ps = employee.payslip_for(Period.from_date(start_date))

    if (ps.nil? || ps.vacation_balance == 0)
      0
    else
      period_days = days_in_period(period)
      (ps.vacation_daily_rate * period_days).round
    end
  end

  def get_tax
    if @tax.nil?
      vac_pay = vacation_pay()
      @tax = Tax.compute_taxes(employee, vac_pay, vac_pay)
    else
      @tax
    end
  end

  private

  def number_of_days(start_date, end_date)
    tmp_start_date = start_date.clone
    holidays = Holiday.days_hash(start_date, end_date)

    count = 0
    while (tmp_start_date <= end_date)
      unless (is_off_day?(tmp_start_date) || holidays.has_key?(tmp_start_date))
        count += 1
      end
      tmp_start_date += 1
    end

    count
  end

  def end_date_after_start
    return if end_date.blank? or start_date.blank?
    errors.add(:end_date, I18n.t(:after_start_date)) if end_date < start_date
  end

  def doesnt_overlap_existing
    return if employee.nil? or start_date.blank? or end_date.blank?
    existing = employee.vacations
    existing = existing.where('id != ?', id) if id
    unless existing.where(overlap_clause).empty?
      errors.add(:base, I18n.t(:Vacation_overlaps))
    end
  end

  def remove_overlapped_work_hours
    overlapped_work_hours.each{ |wh| wh.destroy! }
  end

  def overlap_clause
    Vacation.overlap_clause(start_date, end_date)
  end

  def dont_violate_posted_period
    if new_record?
      if LastPostedPeriod.in_posted_period? start_date
        errors.add :start_date, I18n.t(:cant_be_during_posted_period)
      end
    else
      if start_date_changed? and LastPostedPeriod.in_posted_period? start_date, start_date_was
        errors.add :start_date, I18n.t(:cant_change_during_posted_period)
      end
      if end_date_changed? and LastPostedPeriod.in_posted_period? end_date, end_date_was
        errors.add :end_date, I18n.t(:cant_change_during_posted_period)
      end
    end
  end

  def cant_modify_if_already_paid
    if (self[:paid])
      if start_date_changed?
        errors.add :start_date, I18n.t(:cant_change_paid_record)
      end
      if end_date_changed?
        errors.add :end_date, I18n.t(:cant_change_paid_record)
      end
    end
  end

  def self.overlap_clause(start_date, end_date)
    ["(start_date BETWEEN :start AND :end) OR

app/controllers/vacations_controller.rb
require 'payslip_generator'

class VacationsController < ApplicationController
  include PayslipGenerator

  before_action :set_employee, only: [:index, :new, :days_summary]
  before_action :set_vacation, only: [:edit, :update, :destroy]

  #TODO Find a solution for why Feb 31 saves as Mar 3

  def index
    if @employee
      authorize! :read, @employee

      @vacations = @employee.vacations
      render 'index_for_employee'
    else
      authorize! :admin, Employee

      @period = get_params_period
      @period_vacations = Vacation.for_period(@period)
      @upcoming_vacations = Vacation.upcoming_vacations
    end
  end

  def new
    authorize! :create, Vacation

    @vacation = Vacation.new
    if @employee
      @vacation.employee = @employee
      render 'new_for_employee'
    else
      render 'new'
    end
  end

  def create
    authorize! :create, Vacation

    @vacation = Vacation.new vacation_params
    unless @vacation.valid?
      render :new
      return
    end

    if deconflicted_save
      redirect_user
    end
  end

  def mark_paid
    authorize! :update, Vacation

    @vacation = Vacation.find params[:id]
    @vacation.mark_paid

    if (@vacation.save)
      redirect_user
    end
  end

  def print_voucher
    authorize! :create, Vacation

    @vacation = Vacation.find params[:id]
    @vacation.prep_print
    @vacation.save

    respond_to do |format|
      format.pdf { voucher_generator(@vacation) }
    end
  end

  def edit
    authorize! :update, Vacation

  end

  def update
    authorize! :update, Vacation

    @vacation.update_attributes vacation_params
    unless @vacation.valid?
      render :edit
      return
    end

    if deconflicted_save
      redirect_user
    end
  end

  def destroy
    authorize! :destroy, Vacation

    @vacation.destroy
    redirect_user
  end

  def days_summary
    authorize! :read, @employee

    render layout: false
  end

  private

  def vacation_params
    params.require(:vacation).permit(:employee_id, 'start_date(1i)', 'start_date(2i)',
                                     'start_date(3i)', 'end_date(1i)', 'end_date(2i)',
                                     'end_date(3i)', :start_date, :end_date)
  end

  def set_employee
    @employee = Employee.find(params[:employee_id]) if params[:employee_id]
  end

  def set_vacation
    @vacation = Vacation.find params[:id]
  end

  def deconflicted_save
    if !params[:confirm_delete_work_hours] and @vacation.overlaps_work_hours?
      render 'overlap_alert'
      return false
    end
    @vacation.save!
  end

  def redirect_user
    if (params[:referred_by].present?)
      redirect_to params[:referred_by]
    else
      follow_redirect vacations_path
    end
  end

end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_days_summary.html.erb
<ul class="list-inline">
  <li>
    <b><%= t :Vacation_balance %>:</b>
    <% payslip = Payslip.most_recent(employee)%>
    <% balance = payslip.nil? ? 0 : payslip.vacation_balance %>
    <% period = payslip.nil? ? nil : payslip.period.to_s %>
    <span <%= 'style="color: red;"'.html_safe if balance < 0 %>>
        <%= balance.round(2) %> <% if period %> (as of <%= period %>) <% end %>
    </span>
  </li>
</ul>

app/views/vacations/_vacation_form.html.erb
<%= form_for @vacation, html: {class: 'auto-width'} do |form| %>
  <h2><%= t(:Enter_vacation) %></h2>

  <%= render 'shared/error_messages', errors: @vacation.errors %>

  <% if params[:referred_by].present? %>
    <%= hidden_field_tag "referred_by", params[:referred_by] %>
  <% end %>

  <div class="form-group">
    <%= form.label :employee, t(:Employee) %>
    <%= form.collection_select :employee_id, Employee.all, :id, :full_name_rev,
                               {}, class: 'form-control' %>
  </div>

  <div id="days-summary">
    <% unless @vacation.employee.nil? %>
      <%= render 'days_summary', employee: @vacation.employee %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :start_date, t(:Start_date), style: 'display: block;' %>
    <% if LastPostedPeriod.in_posted_period? @vacation.start_date %>
      <p><%= @vacation.start_date.strftime("%Y %B %e") %></p>
    <% else %>
      <%= form.date_select :start_date, {}, class: 'form-control form-control-inline' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :end_date, t(:End_date), style: 'display: block;' %>
    <%= form.date_select :end_date, {}, class: 'form-control form-control-inline' %>
  </div>

  <%= form.submit t(:Save), class: 'btn btn-primary' %>
<% end %>

app/views/vacations/_vacation_table.html.erb
<table class="table">
  <tr>
    <th><%= t :Employee %></th>
    <th><%= t :Start_date %></th>
    <th><%= t :End_date %></th>
    <th><%= t :Days_per %></th>
    <th><%= t :Paid? %></th>
    <th><%= t :Voucher %></th>
    <th colspan="3"></th>
  </tr>
  <% vacations.each do |vacation| %>
      <tr>
        <td><%= vacation.employee.full_name %></td>
        <td><%= std_datestring vacation.start_date %></td>
        <td><%= std_datestring vacation.end_date %></td>
        <td><%= vacation.days %> <%= t(:Days) %></td>
        <td><%= vacation.paid? ? t(:Yes) : t(:No) %></td>
        <td><%= link_to t(:Print_voucher),  print_voucher_vacation_path(vacation, :format => :pdf) %></td>
        <td>
          <% if vacation.editable? %>
            <%= link_to t(:Mark_paid),  mark_paid_vacation_path(vacation) %></td>
          <% end %>
        </td>
        <% referred_by = request.path %>
        <% referred_by += "?period=#{@period.to_s}" if @period %>
        <td>
          <% if vacation.editable? %>
            <%= link_to t(:Edit), edit_vacation_path(vacation, referred_by: referred_by) %>
          <% end %>
        </td>
        <td>
          <% if vacation.destroyable? %>
            <%= link_to t(:Delete),  vacation_path(vacation, referred_by: referred_by), method: :delete, data: { confirm: t(:Are_you_sure) }  %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

app/views/vacations/days_summary.html.erb
<%= render 'days_summary', employee: @employee %>

app/views/vacations/edit.html.erb
<%= render 'vacation_form' %>

app/views/vacations/index.html.erb
<%= link_to t(:Enter_vacation), new_vacation_path, class: 'btn btn-primary' %>

<h3><%= t(:Vacation_for) %> <%= @period.name %></h3>
<%= render 'shared/period_nav', period: @period, path: vacations_path %>
<% unless @period_vacations.empty? %>
  <%= render 'vacation_table', vacations: @period_vacations %>
<% end %>

<% if @period == Period.current and not @upcoming_vacations.empty? %>
  <h3><%= t(:Other_upcoming_vacation) %></h3>
  <%= render 'vacation_table', vacations: @upcoming_vacations %>
<% end %>

app/views/vacations/index_for_employee.html.erb
<%= link_to "<< #{@employee.full_name}", employee_path(@employee) %>

<h2><%= t :Vacation_for %> <%= @employee.full_name %></h2>

<% if can? :create, Vacation %>
  <%= link_to t(:Enter_vacation), new_employee_vacation_path(@employee, referred_by: request.path), class: 'btn btn-primary', style: 'margin-bottom: 10px;', id: 'enter-vacation-btn' %>
<% end %>

<%= render 'days_summary', employee: @employee %>

<%= render 'vacation_table', vacations: @vacations.reverse_order %>

app/views/vacations/new.html.erb
<%= link_to "<< #{t :Vacation }", vacations_path %>

<%= render 'vacation_form' %>

app/views/vacations/new_for_employee.html.erb
<%= link_to "<< #{@employee.full_name} #{t :Vacation}", employee_vacations_path(@employee) %>

<%= render 'vacation_form' %>

app/views/vacations/overlap_alert.html.erb
<div>
  <h2><%= t :Vacation_for %> <%= @vacation.employee.full_name %></h2>
  <div>
    <label><%= t :Start_date %></label>
    <%= @vacation.start_date %>
  </div>
  <div>
    <label><%= t :End_date %></label>
    <%= @vacation.end_date %>
  </div>
</div>

<div class="error-explanation">
  <div>
    <%= t(:Overlap_message) %>
  </div>
  <a href="javascript:history.back()" class="btn btn-primary"><%= t :No_go_back %></a>
</div>

<table class="table" style="width: auto;">
  <% @vacation.overlapped_work_hours.each do |workhour| %>
    <tr>
      <td>
        <%= workhour.date %>
      </td>
      <td>
        <%= workhour.hours %>
        <%= t(:Hours) %>
      </td>
    </tr>
  <% end %>
</table>
<%= form_for @vacation do |form| %>
  <%= hidden_field_tag :confirm_delete_work_hours, true %>
  <%= form.hidden_field :employee_id %>
  <div style="display: none;">
    <%= form.date_select :start_date %>
    <%= form.date_select :end_date %>
  </div>

  <%= form.submit t(:Save_vacation_and_delete_work_hours), class: 'btn btn-danger' %>
<% end %>

app/views/vacations/print_voucher.html.erb
<h4>Bulletin de Paie - Congé</h4>

<p>
Dates exactes de congé: du <%= @vacation.start_date %> au <%= @vacation.end_date %><br />
Nom du travailleur: <%= @vacation.employee.full_name %><br />
Matricule No. <%= @vacation.employee.id %><br />
Catégoire professionnelle: <%= display_category_roman(@vacation.employee.category) %>-<%= display_echelon(@vacation.employee.echelon) %><br />
Nombre de journées: <%= @vacation.days %> @ <%= @vacation.vacation_pay.fdiv(@vacation.days).round(2) %> soit CFA <%= @vacation.vacation_pay.round %><br />
</p>

<h4>Déductions</h4>

<p>
Taxe Proportionelle: <%= @vacation.get_tax.proportional %><br />
C.A.C.: <%= @vacation.get_tax.cac %><br />
Taxe communale: <%= @vacation.get_tax.communal %><br />
Pension vieillesse 4,2%: <%= @vacation.get_tax.cnps %><br />
Crédit foncier: <%= @vacation.get_tax.ccf %><br />
Audio-visuelle: <%= @vacation.get_tax.crtv %><br />
</p>

<p>
MONTANT DES DEDUCTIONS: <%= @vacation.get_tax.total_tax %><br />
MONTANT DE LA PAIE: <%= ( @vacation.vacation_pay - @vacation.get_tax.total_tax ).round %>
</p>