config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#home"

  resources :vacations, except: [:show] do
    member do
      get 'print_voucher'
      get 'mark_paid'
    end
  end
  resources :misc_payments
  resources :bonuses
  resources :work_loans, only: [ :index, :new, :create, :destroy ]
  resources :departments
  resources :payslip_corrections
  resources :holidays, except: [:show, :new] do
    collection do
      post 'generate/:year', to: 'holidays#generate', as: :generate
    end
  end
  resources :standard_charge_notes, only: [:index, :create, :destroy]
  shallow do
    resources :employees do
      get 'search', on: :collection
      resources :children, except: [:show]
      resources :raises
      resources :loans, except: [:show] do
        resources :loan_payments, except: [:show, :index]
      end
      resources :bonuses, only: [ :index ] do
        collection do
          get 'list_possible', to: 'bonuses#index'
          patch 'unassign'
          patch 'assign'
        end
      end
      resources :work_loans, only: [ :index, :new, :create, :destroy ]
      resources :charges, except: [:edit, :update, :show]
      resources :misc_payments, except: [:edit, :update, :show]
      resources :vacations, except: :show do
        get 'days_summary', on: :collection
      end
      resources :payslips, only: [ :index, :show ]
    end
  end

  resources :supervisors, except: [:show]

  resources 'payslips', only: [ :index, :show ] do
    collection do
      post 'print_multi'
    end
  end

  # Reports index
  get 'reports', to: 'reports#index'
  get 'report_display', to: 'reports#show'
  get 'reports/*report', to: 'home#home' # eliminate gem routes
  get 'multi/reports/*report', to: 'home#home' # eliminate gem routes

  # Payslips
  post 'payslips/process', to: 'payslips#process_employee', as: :payslip_process_employee
  post 'payslips/process_complete', to: 'payslips#process_employee_complete', as: :payslip_process_employee_complete
  post 'payslips/process_all', to: 'payslips#process_all_employees', as: :payslip_process_all
  post 'payslips/process_all_nonrfis', to: 'payslips#process_nonrfis_employees', as: :payslip_process_nonrfis
  post 'payslips/process_all_rfis', to: 'payslips#process_rfis_employees', as: :payslip_process_rfis
  post 'payslips/process_all_bro', to: 'payslips#process_bro_employees', as: :payslip_process_bro
  post 'payslips/process_all_gnro', to: 'payslips#process_gnro_employees', as: :payslip_process_gnro
  post 'payslips/process_all_av', to: 'payslips#process_av_employees', as: :payslip_process_av
  post 'payslips/view_print_nonrfis', to: 'payslips#view_print_nonrfis', as: :view_print_nonrfis
  post 'payslips/view_print_rfis', to: 'payslips#view_print_rfis', as: :view_print_rfis
  post 'payslips/view_print_bro', to: 'payslips#view_print_bro', as: :view_print_bro
  post 'payslips/view_print_gnro', to: 'payslips#view_print_gnro', as: :view_print_gnro
  post 'payslips/view_print_av', to: 'payslips#view_print_av', as: :view_print_av
  post 'payslips/view_print_all', to: 'payslips#view_print_all', as: :view_print_all
  post 'payslips/post_period', to: 'payslips#post_period', as: :payslip_post_period
  post 'payslips/unpost_period', to: 'payslips#unpost_period', as: :payslip_unpost_period

  # Work Hours
  get 'workhours', to: 'work_hours#index', as: :work_hours
  get 'employees/:employee_id/work_hours',      to: 'work_hours#index', as: :employee_work_hours
  get 'employees/:employee_id/work_hours/edit', to: 'work_hours#edit',  as: :edit_employee_work_hours
  post 'employees/:employee_id/work_hours',    to: 'work_hours#update', as: :update_employee_work_hours
  post 'employees/work_hours_fill_all', to: 'work_hours#update_all', as: :fill_all_employees_work_hours

  # Administration
  get 'admin/index'
  get 'admin/manage_variables'
  get 'admin/manage_wages'
  get 'admin/manage_wage_show'
  get 'admin/journal_report'
  post 'admin/manage_wage_show', to: 'admin#manage_wage_update'
  get 'admin/timesheet', to: 'admin#timesheet', as: :generate_timesheets
  get 'admin/timesheets', to: 'admin#timesheets', as: :timesheet_pdf
  get 'admin/estimatepay', to: 'admin#estimate_pay', as: :estimate_pay
  post 'admin/estimate', to: 'admin#estimate_pay_process', as: :estimate_pay_post

  resources :users, except: [ 'show' ]

  # Session Controller
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Mock Controller
  get 'mock', to: "mock#home"
  get 'mock_employees', to: 'mock#employees'
  get 'mock_vacation', to: 'mock#vacation'
  get 'charges', to: 'mock#charges'
  get 'hours/edit', to: 'mock#hours_edit'
end

app/views/admin/estimate_pay.html.erb
<% provide :title,  t(:Administration) %>

    <h2><%= t(:Estimate_pay) %></h2>

<h4><%= t(:How_it_works) %></h4>

<p><%= t(:Estimate_step_1) %></p>

<%= form_with url: "#{estimate_pay_post_path()}.json", id: 'estimate-form' do |f| %>
  <div class="form-group">
    <%= label_tag :estimate, t(:Estimate) %>
    <%= text_field_tag :estimate %>
  </div>
  <div class="form-group">
    <%= submit_tag t(:Continue) %>
  </div>
<% end %>

<p><%= t(:Estimate_step_2) %></p>

<p class="bg-info">
  <span><%= t(:Employees_pay) %></span><br />
  <strong><span id="estimate-response"></span></strong> <span><strong>CFA</strong></span>
</p>

<hr />

<h4><%= t(:How_the_numbers_are_calculated) %></h4>

<p> <%= t(:Basic_formula) %> </p>

<pre> <%= t(:Dept_charge_formula) %> </pre>

<p>
<%= t(:Dept_credit_foncier_explanation) %>
  <pre><%= t(:Taxable_wage) %> * <%= SystemVariable.value(:dept_credit_foncier) %></pre>
<%= t(:Dept_cnps_explanation) %>
  <pre><%= t(:Taxable_wage) %> * <%= SystemVariable.value(:dept_cnps) %></pre>
</p>

<p>
<%= t(:If_taxable_wage) %> &gt; <%= SystemVariable.value(:cnps_ceiling) %> <%= t(:Then) %>
  <pre>Department CNPS = ( <%= t(:Taxable_wage) %> * <%= SystemVariable.value(:dept_cnps_w_ceil) %> + <%= SystemVariable.value(:dept_cnps_max_base) %>)</pre>
</p>

<p>
  <%= t(:Percentage_explanation) %>
</p>

app/views/admin/index.html.erb
<% provide(:title, t(:Administration)) %>

<div class="lead">
  <div class="row">
    <div class="col-md-12">
      <h2>Site Administration</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Payslip_management), payslips_path %></div>
    <div class="col-md-8"><%= t(:Payslips_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Payslip_corrections), payslip_corrections_path %></div>
    <div class="col-md-8"><%= t(:Payslip_corrections_description) %></div>
  </div>

  <hr />

  <div class="row">
    <div class="col-md-4"><%= link_to t(:Holidays), holidays_path %></div>
    <div class="col-md-8"><%= t(:Holidays_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Print_timesheets), generate_timesheets_path %></div>
    <div class="col-md-8"><%= t(:Print_timesheets_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Standard_charge_notes), standard_charge_notes_path %></div>
    <div class="col-md-8"><%= t(:Charges_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Supervisors), supervisors_path %></div>
    <div class="col-md-8"><%= t(:Supervisors_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Users), users_path %></div>
    <div class="col-md-8"><%= t(:Users_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Department_management), departments_path %></div>
    <div class="col-md-8"><%= t(:Departments_admin_description) %></div>
  </div>

  <hr />

  <div class="row">
    <div class="col-md-4"><%= link_to t(:journal_report), admin_journal_report_path %></div>
    <div class="col-md-8"><%= t(:Journal_report_description) %></div>
  </div>

  <hr />

  <div class="row">
    <div class="col-md-4"><%= link_to t(:Manage_wages), admin_manage_wages_path %></div>
    <div class="col-md-8"><%= t(:Wages_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Manage_variables), admin_manage_variables_path %></div>
    <div class="col-md-8"><%= t(:Variables_admin_description) %></div>
  </div>
  <div class="row">
    <div class="col-md-4"><%= link_to t(:Estimate_pay), estimate_pay_path %></div>
    <div class="col-md-8"><%= t(:Estimate_pay_description) %></div>
  </div>
</div>

app/views/admin/journal_report.html.erb
<% provide :title,  t(:Administration) %>

<h2><%= t(:Journal_report) %> : <%= @period.name %></h2>

<div class="col-md-6">
  <code>
    Total Debits: <%= number_to_currency(@total_debit, unit: 'CFA', locale: :cm) %><br />
    Total Credits: <%= number_to_currency(@total_credit, unit: 'CFA', locale: :cm) %><br />
    Difference: <%= number_to_currency((@total_debit - @total_credit), unit: '', locale: :cm) %><br />
  </code>
</div>

<div class="col-md-6 text-right">
  <div class="alert alert-info">

    <%= form_tag(admin_journal_report_path(), method: 'get', class: 'form-inline') %>
      <div class="form-group">
        <label><%= t :Period %></label>
        <%= select_tag 'period',
                       options_for_select(@periods), { prompt: t(:Select_a_period, scope: :reports), class: 'form-control' } %>
      </div>
      <%= submit_tag t(:Display), { class: 'btn btn-primary', data: {disable_with: false} } %>
    </form>

    <em>All data is for the period: <%= @period %></em>
  </div>
</div>

<table class="table journal-table table-condensed table-bordered table-hover">
<tr>
  <th class="col-sm-2">Account Number</th>
  <th class="col-sm-4">Account Name</th>
  <th class="col-sm-4">Description</th>
  <th class="col-sm-1 text-nowrap" align="right">DEBIT</th>
  <th class="col-sm-1 text-nowrap" align="right">CREDIT</th>
  <th class="col-sm-1 text-nowrap" align="right">Balance</th>
</tr>
<tr>

<% balance = 0 %>

<% @report_data.each do |line| %>

  <% balance -= line[:debit] %>
  <% balance += line[:credit] %>
<tr>
  <td><%= line[:dept_account] %></td>
  <td><%= line[:dept_name] %></td>
  <td><%= line[:dept_note] %></td>
  <td class="text-nowrap" align="right"><%= number_to_currency(line[:debit], unit: '', locale: :cm) %></td>
  <td class="text-nowrap" align="right"><%= number_to_currency(line[:credit], unit: '', locale: :cm) %></td>
  <td class="text-nowrap" align="right"><%= number_to_currency(balance, unit: '', locale: :cm) %></td>
</tr>
<% end %>
</table>

app/views/admin/manage_variables.html.erb
<% provide(:title, t(:Administration)) %>

<h1>View System Variables</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Value</th>
  </tr>
<% SystemVariable.get_defaults.each do |var| %>
  <tr>
    <td><%= var %></td>
    <td><%= SystemVariable.value(var) %></td>
  </tr>
<% end %>
<% SystemVariable.all.each do |var| %>
  <tr>
    <td><%= var.key %></td>
    <td><%= var.value %></td>
  </tr>
<% end %>
</table>

app/views/admin/manage_wage_show.html.erb
<% provide(:title, t(:Administration)) %>

<h2><%= t(:Manage_wages) %></h2>

<h4><%= t(:Wage_information_for) %>: <%= t(:Category) %>: <%= @wage.category %>, <%= t(:Echelon) %>: <%= @wage.echelon %>, <%= t(:Echelon_alt) %>: <%= @wage.echelonalt %></h4>

<% if @wage.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@wage.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
    <% @wage.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br />

<%= form_for :wage do |f| %>
   <input type="hidden" name="category" value="<%= @wage.category %>" />
   <input type="hidden" name="echelon" value="<%= @wage.echelon %>" />
   <input type="hidden" name="echelonalt" value="<%= @wage.echelonalt %>" />

  <div class="form-group">
    <%= f.label :basewage, t(:Base_wage) %>
    <%= f.text_field :basewage, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :basewageb, t(:Base_wage_b)  %>
    <%= f.text_field :basewageb , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :basewagec, t(:Base_wage_c)  %>
    <%= f.text_field :basewagec, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :basewaged, t(:Base_wage_d)  %>
    <%= f.text_field :basewaged, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :basewagee, t(:Base_wage_e)  %>
    <%= f.text_field :basewagee, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t(:Update), class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/admin/manage_wage_update.html.erb
<% provide(:title, t(:Administration)) %>

<pre><%= @wage.errors.inspect %></pre>

<pre><%= @wage.inspect %></pre>

app/views/admin/manage_wages.html.erb
<% provide(:title, t(:Administration)) %>

<h2><%= t(:Manage_wages) %></h2>

<table class="table table-striped">
  <tr>
  <th><%= t(:Category) %></th>
  <th><%= t(:Echelon) %></th>
  <th><%= t(:Echelon_alt) %></th>
  <th><%= t(:Base_wage) %></th>
  <th><%= t(:Base_wage_b) %></th>
  <th><%= t(:Base_wage_c) %></th>
  <th><%= t(:Base_wage_d) %></th>
  <th><%= t(:Base_wage_e) %></th>
  <th><%= t(:Edit) %></th>
  </tr>
<% @wages.each do |wage| %>
  <tr>
    <td><%= wage.category %></td>
    <td><%= wage.echelon %></td>
    <td><%= wage.echelonalt %></td>
    <td><%= wage.basewage %></td>
    <td><%= wage.basewageb %></td>
    <td><%= wage.basewagec %></td>
    <td><%= wage.basewaged %></td>
    <td><%= wage.basewagee %></td>
    <td><%= link_to t(:Edit), admin_manage_wage_show_path(category: wage.category, echelon: wage.echelon, echelonalt: wage.echelonalt) %></td>
  </tr>
<% end %>
</table>

app/views/admin/timesheet.html.erb
<% provide :title, t(:Print_timesheets) %>

<p>
  <%= link_to "<< #{t(:Administration)}", admin_index_path %>
</p>


<h2><%= t(:Choose_options_for_timesheets) %></h2>

<%= form_tag(timesheet_pdf_url() + ".pdf", method: 'get') %>

  <div class="form-group">
    <label><%= t :Period %></label>
    <%= select_tag 'period',
                   options_from_collection_for_select(@periods, 'to_s', 'name', @current.to_s), { prompt: t(:Select_a_period, scope: :reports), class: 'form-control' } %>
  </div>

  <div class="form-group">
    <label><%= t :Employee %></label>
    <%= select_tag 'employees',
                    options_from_collection_for_select(@employees, 'id', 'full_name_rev', @employees.map(&:id)), { multiple: true, size: 10, class: 'form-control' } %>
  </div>

  <div class="form-group">
    <label><%= t :Announcements %></label>
    <%= text_area(:timesheet, :announcement, class: 'form-control') %>
  </div>

  <%= submit_tag t(:Display), { class: 'btn btn-primary' } %>

</form>