config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#home"

  resources :vacations, except: [:show] do
    member do
      get 'print_voucher'
      get 'mark_paid'
    end
  end
  resources :misc_payments
  resources :bonuses
  resources :work_loans, only: [ :index, :new, :create, :destroy ]
  resources :departments
  resources :payslip_corrections
  resources :holidays, except: [:show, :new] do
    collection do
      post 'generate/:year', to: 'holidays#generate', as: :generate
    end
  end
  resources :standard_charge_notes, only: [:index, :create, :destroy]
  shallow do
    resources :employees do
      get 'search', on: :collection
      resources :children, except: [:show]
      resources :raises
      resources :loans, except: [:show] do
        resources :loan_payments, except: [:show, :index]
      end
      resources :bonuses, only: [ :index ] do
        collection do
          get 'list_possible', to: 'bonuses#index'
          patch 'unassign'
          patch 'assign'
        end
      end
      resources :work_loans, only: [ :index, :new, :create, :destroy ]
      resources :charges, except: [:edit, :update, :show]
      resources :misc_payments, except: [:edit, :update, :show]
      resources :vacations, except: :show do
        get 'days_summary', on: :collection
      end
      resources :payslips, only: [ :index, :show ]
    end
  end

  resources :supervisors, except: [:show]

  resources 'payslips', only: [ :index, :show ] do
    collection do
      post 'print_multi'
    end
  end

  # Reports index
  get 'reports', to: 'reports#index'
  get 'report_display', to: 'reports#show'
  get 'reports/*report', to: 'home#home' # eliminate gem routes
  get 'multi/reports/*report', to: 'home#home' # eliminate gem routes

  # Payslips
  post 'payslips/process', to: 'payslips#process_employee', as: :payslip_process_employee
  post 'payslips/process_complete', to: 'payslips#process_employee_complete', as: :payslip_process_employee_complete
  post 'payslips/process_all', to: 'payslips#process_all_employees', as: :payslip_process_all
  post 'payslips/process_all_nonrfis', to: 'payslips#process_nonrfis_employees', as: :payslip_process_nonrfis
  post 'payslips/process_all_rfis', to: 'payslips#process_rfis_employees', as: :payslip_process_rfis
  post 'payslips/process_all_bro', to: 'payslips#process_bro_employees', as: :payslip_process_bro
  post 'payslips/process_all_gnro', to: 'payslips#process_gnro_employees', as: :payslip_process_gnro
  post 'payslips/process_all_av', to: 'payslips#process_av_employees', as: :payslip_process_av
  post 'payslips/view_print_nonrfis', to: 'payslips#view_print_nonrfis', as: :view_print_nonrfis
  post 'payslips/view_print_rfis', to: 'payslips#view_print_rfis', as: :view_print_rfis
  post 'payslips/view_print_bro', to: 'payslips#view_print_bro', as: :view_print_bro
  post 'payslips/view_print_gnro', to: 'payslips#view_print_gnro', as: :view_print_gnro
  post 'payslips/view_print_av', to: 'payslips#view_print_av', as: :view_print_av
  post 'payslips/view_print_all', to: 'payslips#view_print_all', as: :view_print_all
  post 'payslips/post_period', to: 'payslips#post_period', as: :payslip_post_period
  post 'payslips/unpost_period', to: 'payslips#unpost_period', as: :payslip_unpost_period

  # Work Hours
  get 'workhours', to: 'work_hours#index', as: :work_hours
  get 'employees/:employee_id/work_hours',      to: 'work_hours#index', as: :employee_work_hours
  get 'employees/:employee_id/work_hours/edit', to: 'work_hours#edit',  as: :edit_employee_work_hours
  post 'employees/:employee_id/work_hours',    to: 'work_hours#update', as: :update_employee_work_hours
  post 'employees/work_hours_fill_all', to: 'work_hours#update_all', as: :fill_all_employees_work_hours

  # Administration
  get 'admin/index'
  get 'admin/manage_variables'
  get 'admin/manage_wages'
  get 'admin/manage_wage_show'
  get 'admin/journal_report'
  post 'admin/manage_wage_show', to: 'admin#manage_wage_update'
  get 'admin/timesheet', to: 'admin#timesheet', as: :generate_timesheets
  get 'admin/timesheets', to: 'admin#timesheets', as: :timesheet_pdf
  get 'admin/estimatepay', to: 'admin#estimate_pay', as: :estimate_pay
  post 'admin/estimate', to: 'admin#estimate_pay_process', as: :estimate_pay_post

  resources :users, except: [ 'show' ]

  # Session Controller
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Mock Controller
  get 'mock', to: "mock#home"
  get 'mock_employees', to: 'mock#employees'
  get 'mock_vacation', to: 'mock#vacation'
  get 'charges', to: 'mock#charges'
  get 'hours/edit', to: 'mock#hours_edit'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    if current_user.admin?
      @alerts = Alert.get_all
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_activity_feed.html.erb
<% if current_user.admin? %>
    <h2><%= t :Activity_feed %></h2>
    <hr>
    <ul class="list-unstyled feed">
      <% feed_items = PayrollAudit.feed_items()
         feed_items.each do |item| %>
        <li>
          <strong class="text-capitalize"><%= item[:title] %> : </strong>
          <p><%= item[:text] %></p>
          <i><%= item[:when] %> by <%= item[:who] %></i>
        </li>
      <% end %>
      <li>
        <%= link_to t(:More_history), '#' %>
      </li>
    </ul>
<% end %>

app/views/home/_alerts.erb
<% if current_user.admin? and not @alerts.empty? %>
  <h2><%= t :Alerts %></h2>
  <hr>
  <ul class="list-unstyled feed">
    <% @alerts.each do |alert| %>
      <li>
        <p>
          <%= alert.text %>
          <%= link_to t(:View), alert.object unless alert.object.nil? %>
        </p>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/home/home.html.erb
<% if alert %>
  <p id="permissions-error" class="bg-danger"><%= alert %></p>
<% end %>

<%= render 'employees/search_form' %>

<div class="row">
  <div class="col-md-6">
    <h2 id="home"><%= t :Tasks %></h2>
    <hr />
    <ul class="list-unstyled" id="link-list">

      <li><%= link_to t(:Employees), employees_path %></li>

      <% if can? :create, WorkHour %>
        <li><%= link_to t(:Hours), work_hours_path, id: 'hours-link' %></li>
      <% end %>

      <% if can? :create, Vacation %>
        <li><%= link_to t(:Vacation), vacations_path, id: 'vacations-link' %></li>
      <% end %>

      <li><%= link_to t(:Misc_payments), misc_payments_path, id: 'misc-payments-link' %></li>

      <% if can? :read, Bonus %>
        <li><%= link_to t(:Bonuses), bonuses_path %></li>
      <% end %>

      <% if can? :read, WorkLoan %>
        <li><%= link_to t(:Work_loans), work_loans_path, id: 'work-loans-link' %></li>
      <% end %>

      <% if can? :read, ReportsController %>
        <li><%= link_to t(:Reports), reports_path, id: 'reports-link' %></li>
      <% end %>

      <% if can? :read, AdminController %>
        <hr />
        <li><%= link_to t(:Administration), admin_index_path, id: 'admin-link' %></li>
      <% end %>

    </ul>
  </div>
  <div class="col-md-6">
    <%= render "alerts" %>
    <%= render "activity_feed" %>
  </div>
</div>