config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#home"

  resources :vacations, except: [:show] do
    member do
      get 'print_voucher'
      get 'mark_paid'
    end
  end
  resources :misc_payments
  resources :bonuses
  resources :work_loans, only: [ :index, :new, :create, :destroy ]
  resources :departments
  resources :payslip_corrections
  resources :holidays, except: [:show, :new] do
    collection do
      post 'generate/:year', to: 'holidays#generate', as: :generate
    end
  end
  resources :standard_charge_notes, only: [:index, :create, :destroy]
  shallow do
    resources :employees do
      get 'search', on: :collection
      resources :children, except: [:show]
      resources :raises
      resources :loans, except: [:show] do
        resources :loan_payments, except: [:show, :index]
      end
      resources :bonuses, only: [ :index ] do
        collection do
          get 'list_possible', to: 'bonuses#index'
          patch 'unassign'
          patch 'assign'
        end
      end
      resources :work_loans, only: [ :index, :new, :create, :destroy ]
      resources :charges, except: [:edit, :update, :show]
      resources :misc_payments, except: [:edit, :update, :show]
      resources :vacations, except: :show do
        get 'days_summary', on: :collection
      end
      resources :payslips, only: [ :index, :show ]
    end
  end

  resources :supervisors, except: [:show]

  resources 'payslips', only: [ :index, :show ] do
    collection do
      post 'print_multi'
    end
  end

  # Reports index
  get 'reports', to: 'reports#index'
  get 'report_display', to: 'reports#show'
  get 'reports/*report', to: 'home#home' # eliminate gem routes
  get 'multi/reports/*report', to: 'home#home' # eliminate gem routes

  # Payslips
  post 'payslips/process', to: 'payslips#process_employee', as: :payslip_process_employee
  post 'payslips/process_complete', to: 'payslips#process_employee_complete', as: :payslip_process_employee_complete
  post 'payslips/process_all', to: 'payslips#process_all_employees', as: :payslip_process_all
  post 'payslips/process_all_nonrfis', to: 'payslips#process_nonrfis_employees', as: :payslip_process_nonrfis
  post 'payslips/process_all_rfis', to: 'payslips#process_rfis_employees', as: :payslip_process_rfis
  post 'payslips/process_all_bro', to: 'payslips#process_bro_employees', as: :payslip_process_bro
  post 'payslips/process_all_gnro', to: 'payslips#process_gnro_employees', as: :payslip_process_gnro
  post 'payslips/process_all_av', to: 'payslips#process_av_employees', as: :payslip_process_av
  post 'payslips/view_print_nonrfis', to: 'payslips#view_print_nonrfis', as: :view_print_nonrfis
  post 'payslips/view_print_rfis', to: 'payslips#view_print_rfis', as: :view_print_rfis
  post 'payslips/view_print_bro', to: 'payslips#view_print_bro', as: :view_print_bro
  post 'payslips/view_print_gnro', to: 'payslips#view_print_gnro', as: :view_print_gnro
  post 'payslips/view_print_av', to: 'payslips#view_print_av', as: :view_print_av
  post 'payslips/view_print_all', to: 'payslips#view_print_all', as: :view_print_all
  post 'payslips/post_period', to: 'payslips#post_period', as: :payslip_post_period
  post 'payslips/unpost_period', to: 'payslips#unpost_period', as: :payslip_unpost_period

  # Work Hours
  get 'workhours', to: 'work_hours#index', as: :work_hours
  get 'employees/:employee_id/work_hours',      to: 'work_hours#index', as: :employee_work_hours
  get 'employees/:employee_id/work_hours/edit', to: 'work_hours#edit',  as: :edit_employee_work_hours
  post 'employees/:employee_id/work_hours',    to: 'work_hours#update', as: :update_employee_work_hours
  post 'employees/work_hours_fill_all', to: 'work_hours#update_all', as: :fill_all_employees_work_hours

  # Administration
  get 'admin/index'
  get 'admin/manage_variables'
  get 'admin/manage_wages'
  get 'admin/manage_wage_show'
  get 'admin/journal_report'
  post 'admin/manage_wage_show', to: 'admin#manage_wage_update'
  get 'admin/timesheet', to: 'admin#timesheet', as: :generate_timesheets
  get 'admin/timesheets', to: 'admin#timesheets', as: :timesheet_pdf
  get 'admin/estimatepay', to: 'admin#estimate_pay', as: :estimate_pay
  post 'admin/estimate', to: 'admin#estimate_pay_process', as: :estimate_pay_post

  resources :users, except: [ 'show' ]

  # Session Controller
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Mock Controller
  get 'mock', to: "mock#home"
  get 'mock_employees', to: 'mock#employees'
  get 'mock_vacation', to: 'mock#vacation'
  get 'charges', to: 'mock#charges'
  get 'hours/edit', to: 'mock#hours_edit'
end

app/controllers/bonuses_controller.rb
class BonusesController < ApplicationController
  before_action :set_bonus, only: [:show, :edit, :update, :destroy]
  before_action :set_employee, only: [:index, :new, :assign, :unassign]

  def index
    authorize! :read, Bonus

    @bonuses = Bonus.all
    if (@employee)
      render 'list_possible'
    end
  end

  def show
    authorize! :read, Bonus
  end

  def assign
    authorize! :update, Bonus

    bonuses_to_assign_hash = params[:bonus]
    Bonus.assign_to_employee(@employee, bonuses_to_assign_hash)

    redirect_to employee_url(@employee)
  end

  def unassign
    authorize! :update, Bonus

    bonus = Bonus.find(params[:bonus][:b])
    @employee.bonuses.delete(bonus)

    redirect_to employee_url(@employee)
  end

  def new
    authorize! :create, Bonus

    @bonus = Bonus.new
    if (@employee)
      @bonus.employees << @employee
      render 'new_for_employee'
    else
      render 'new'
    end
  end

  def edit
    authorize! :update, Bonus
  end

  def create
    authorize! :create, Bonus

    @bonus = Bonus.new(bonus_params)

    if @bonus.save
      redirect_to @bonus, notice: 'Bonus was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize! :update, Bonus

    if @bonus.update(bonus_params)
      redirect_to @bonus, notice: 'Bonus was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, Bonus

    @bonus.destroy
    redirect_to bonuses_url, notice: 'Bonus was successfully destroyed.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_bonus
      @bonus = Bonus.find(params[:id])
    end

    def set_employee
      @employee = Employee.find(params[:employee_id]) if params[:employee_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bonus_params
      params.require(:bonus).permit(
          :name,
          :quantity,
          :bonus_type,
          :minimum,
          :maximum,
          :comment,
          :ext_quantity,
          :use_caisse,
          :post_tax
      )
    end
end

app/helpers/bonuses_helper.rb
module BonusesHelper
end

app/views/bonuses/_form.html.erb
<%= form_for bonus, html: {class: 'auto-width'} do |form| %>
  <%= render 'shared/error_messages', errors: bonus.errors %>

  <div class="form-group">
    <%= form.label t(:Name) %>
    <%= form.text_field :name, id: :bonus_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label t(:Type) %>
    <%= form.select :bonus_type, options_for_select(Bonus.bonus_types.keys.collect{ |key| [t(key), key] }, bonus.bonus_type), {id: :bonus_bonus_type}, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label t(:Quantity), style: 'display: block;' %>
    <%= form.text_field :ext_quantity, id: :bonus_quantity, class: 'form-control form-control-inline' %>
    <span id='quantity-unit'>FCFA</span>
  </div>

  <div class="form-group">
    <%= form.label t(:Minimum), style: 'display: block;' %>
    <%= form.text_field :minimum, id: :minimum, class: 'form-control form-control-inline' %>
  </div>

  <div class="form-group">
    <%= form.label t(:Maximum), style: 'display: block;' %>
    <%= form.text_field :maximum, id: :maximum, class: 'form-control form-control-inline' %>
  </div>

  <div class="form-group">
    <%= form.label t(:Comment) %>
    <%= form.text_field :comment, id: :bonus_comment, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label t(:Use_caisse) %>
    <%= form.check_box "use_caisse", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label t(:Apply_after_tax_q) %><br />
    <%= t(:Note_after_tax_bonus) %>
    <%= form.check_box "post_tax", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit t(:Save), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/bonuses/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <% if @employee %>
        <th></th>
      <% end %>
      <th><%= t(:Name) %></th>
      <th><%= t(:Quantity) %></th>
      <th><%= t(:Comment) %></th>
      <th><%= t(:Minimum) %></th>
      <th><%= t(:Maximum) %></th>
      <th><%= t(:Use_caisse) %></th>
      <th><%= t(:After_tax) %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @bonuses.each do |bonus| %>
      <tr>
        <% if @employee %>
          <td>
            <%= check_box_tag("bonus[#{bonus.id}]", 1, @employee.bonuses.include?(bonus)) %>
          </td>
        <% end %>
        <td><%= link_to bonus.name, edit_bonus_path(bonus) %></td>
        <td><%= bonus.display_quantity %> <% if bonus.base_percentage? %> <span style="color:red;">of base</span><% end %></td>
        <td><%= bonus.comment %></td>
        <td><%= bonus.minimum %></td>
        <td><%= bonus.maximum %></td>
        <td><%= bonus.use_caisse == false ? "" : t(:Yes) %></td>
        <td><% if bonus.post_tax == false %>
                 <%= t(:Applied_before_tax) %>
               <% else %>
                 <span style="color:red;font-weight:bold;"><%= t(:Applied_after_tax) %></span>
            <% end %>
        </td>
        <% unless @employee %>
          <td><%= link_to t(:Edit), edit_bonus_path(bonus) %></td>
          <td><%= link_to t(:Delete), bonus, method: :delete, data: { confirm: t(:Are_you_sure) } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bonuses/edit.html.erb
<h1><%= t(:Editing_bonus) %></h1>

<%= render 'form', bonus: @bonus %>

<%= link_to t(:Show), @bonus %> |
<%= link_to t(:Back), bonuses_path %>

app/views/bonuses/index.html.erb
<% provide :title, t(:Bonuses) %>

<%= link_to t(:New_bonus), new_bonus_path, class: 'btn btn-primary' %>

<%= render "index" %>

app/views/bonuses/list_possible.html.erb
<%= link_to("<< #{t(:Return_to)} #{@employee.full_name}", employee_url(@employee)) %><br />

<h1><%= t('Select_bonuses_to_be_assigned') %> <%= @employee.full_name %></h1>

<%= link_to t(:Manage_bonuses), bonuses_path %>

<%= form_for @employee, url: { action: "assign" } do |f| %>

<%= render "index" %>

<%= f.submit t(:Assign_to_employee), class: 'btn btn-primary' %>

<% end %>

app/views/bonuses/new.html.erb
<% provide(:title, t(:New_bonus)) %>

<%= link_to "<< #{t(:Bonuses)}", bonuses_path %>

<%= render 'form', bonus: @bonus %>

app/views/bonuses/new_for_employee.html.erb
<h1><%= t(:New_bonus) %> for <%= @employee.full_name %></h1>

<%= render 'form', bonus: @bonus %>

<%= link_to t(:Back), bonuses_path %>

app/views/bonuses/show.html.erb
<p>
  <strong><%= t(:Name) %>:</strong>
  <%= @bonus.name %>
</p>

<p>
  <strong><%= t(:Quantity) %>:</strong>
  <%= @bonus.display_quantity %>
</p>

<p>
  <strong><%= t(:Type) %>:</strong>
  <%= @bonus.bonus_type %>
</p>

<p>
  <strong><%= t(:Minimum) %>:</strong>
  <%= @bonus.minimum %>
</p>

<p>
  <strong><%= t(:Maximum) %>:</strong>
  <%= @bonus.maximum %>
</p>

<p>
  <strong><%= t(:Comment) %>:</strong>
  <%= @bonus.comment %>
</p>

<p>
  <strong><%= t(:Use_caisse) %>:</strong>
  <%= @bonus.use_caisse %>
</p>

<p>
  <strong><%= t(:After_tax) %>:</strong>
  <%= @bonus.post_tax %>
</p>

<%= link_to t(:Edit), edit_bonus_path(@bonus) %> |
<%= link_to t(:Back), bonuses_path %>